#file: noinspection SpellCheckingInspection
services:
  desafio_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d app_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env

  desafio_app:
    image: desafio_infog2
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      desafio_database:
        condition: service_healthy
    env_file:
      - .env_prod

volumes:
  pgdata: