#file: noinspection SpellCheckingInspection
services:
  desafio_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  desafio_app:
    image: desafio_infog2
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - desafio_database
    env_file:
      - .env

volumes:
  pgdata: