"""add delete cascade to order products

Revision ID: bd2e537f84f9
Revises: d26734cf840e
Create Date: 2025-05-25 22:16:24.125281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2e537f84f9'
down_revision: Union[str, None] = 'd26734cf840e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_product_order_id_fkey'), 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_order_id_fkey'), 'order_product', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
