"""add client to order

Revision ID: d26734cf840e
Revises: a5b593a8f775
Create Date: 2025-05-25 19:26:39.021243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26734cf840e'
down_revision: Union[str, None] = 'a5b593a8f775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'client_id')
    op.alter_column('order_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_product', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
